# Site settings
title: Duke duleorlovic - Ruby developer
email: dusan.orlovic@trk-inovacije.com
description: "I am writing here some toughts during my work in Ruby on Rails"
baseurl: "http://orlovic.github.io/blog"
url: "http://orlovic.github.io/blog"
twitter_username: duleorlovic
github_username:  duleorlovic

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile 
